/**
 ** Account-Abstraction (EIP-4337) singleton EntryPoint implementation.
 ** Only one instance required on each chain.
 **/
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.12;

/* solhint-disable avoid-low-level-calls */
/* solhint-disable no-inline-assembly */
/* solhint-disable reason-string */

import '../libs/LibUserOperation.sol';

interface IWasd3rDexManager {
  /**
   * Is the input address Dex Superuser?
   * @param addr address to check
   */
  function isDexSu(address addr) external view returns (bool);

  /**
   * Is the input address Dex Admin?
   * @param addr address to check
   */
  function isDexAdmin(address addr) external view returns (bool);

  /**
   * Simulate a call to account.validateUserOp and paymaster.validatePaymasterUserOp.
   * @dev this method always revert. Successful result is ValidationResult error. other errors are failures.
   * @dev The node must also verify it doesn't use banned opcodes, and that it doesn't reference storage outside the account's data.
   * @param userOp the user operation to validate.
   */
  function simulateValidation(UserOperation calldata userOp) external;

  /**
   * gas and return values during simulation
   * @param preOpGas the gas used for validation (including preValidationGas)
   * @param prefund the required prefund for this operation
   * @param sigFailed validateUserOp's (or paymaster's) signature check failed
   * @param validAfter - first timestamp this UserOp is valid (merging account and paymaster time-range)
   * @param validUntil - last timestamp this UserOp is valid (merging account and paymaster time-range)
   * @param paymasterContext returned by validatePaymasterUserOp (to be passed into postOp)
   */
  struct ReturnInfo {
    uint256 preOpGas;
    uint256 prefund;
    bool sigFailed;
    uint48 validAfter;
    uint48 validUntil;
    bytes paymasterContext;
  }

  /**
   * returned aggregated signature info.
   * the aggregator returned by the account, and its current stake.
   */
  struct AggregatorStakeInfo {
    address aggregator;
    StakeInfo stakeInfo;
  }

  /**
   * Get counterfactual sender address.
   *  Calculate the sender contract address that will be generated by the initCode and salt in the UserOperation.
   * this method always revert, and returns the address in SenderAddressResult error
   * @param initCode the constructor code to be passed into the UserOperation.
   */
  function getSenderAddress(bytes memory initCode) external;

  /**
   * simulate full execution of a UserOperation (including both validation and target execution)
   * this method will always revert with "ExecutionResult".
   * it performs full validation of the UserOperation, but ignores signature error.
   * an optional target address is called after the userop succeeds, and its value is returned
   * (before the entire call is reverted)
   * Note that in order to collect the the success/failure of the target call, it must be executed
   * with trace enabled to track the emitted events.
   * @param op the UserOperation to simulate
   * @param target if nonzero, a target address to call after userop simulation. If called, the targetSuccess and targetResult
   *        are set to the return from that call.
   * @param targetCallData callData to pass to target address
   */
  function simulateHandleOp(UserOperation calldata op, address target, bytes calldata targetCallData) external;
}
